// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSiHt-uFKOSDJ8mEnWiy51ee-7-Rcv7RQ',
    appId: '1:982006064410:web:9a50409a819447aa3ef8a3',
    messagingSenderId: '982006064410',
    projectId: 'order-management-b652b',
    authDomain: 'order-management-b652b.firebaseapp.com',
    storageBucket: 'order-management-b652b.firebasestorage.app',
    measurementId: 'G-QQQ4N8JZQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWerR78S_k512O_S2nMmbmscoBApYEHms',
    appId: '1:982006064410:android:f320f61f8f0632623ef8a3',
    messagingSenderId: '982006064410',
    projectId: 'order-management-b652b',
    storageBucket: 'order-management-b652b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrrwapeKs71tQnH2FZcc7o4K72Zb2Yr8',
    appId: '1:982006064410:ios:d2bceb67bbe997ad3ef8a3',
    messagingSenderId: '982006064410',
    projectId: 'order-management-b652b',
    storageBucket: 'order-management-b652b.firebasestorage.app',
    iosBundleId: 'com.example.deviceCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFrrwapeKs71tQnH2FZcc7o4K72Zb2Yr8',
    appId: '1:982006064410:ios:d2bceb67bbe997ad3ef8a3',
    messagingSenderId: '982006064410',
    projectId: 'order-management-b652b',
    storageBucket: 'order-management-b652b.firebasestorage.app',
    iosBundleId: 'com.example.deviceCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSiHt-uFKOSDJ8mEnWiy51ee-7-Rcv7RQ',
    appId: '1:982006064410:web:fcf2f425c31fa2983ef8a3',
    messagingSenderId: '982006064410',
    projectId: 'order-management-b652b',
    authDomain: 'order-management-b652b.firebaseapp.com',
    storageBucket: 'order-management-b652b.firebasestorage.app',
    measurementId: 'G-QX13QPRF89',
  );
}
